repo:
  scanPath: ./repos
  readme:
    - readme
    - README
    - readme.md
    - README.md
  mainBranch:
    - master
    - main
meta:
  title: git good
  description: i think it's a skill issue
server:
  name: localhost
  host: 127.0.0.1
  port: 8080
